#!/bin/sh

# Simple shell script to configure and run a samba-dc master/slave pair on separate docker machines.

# Note: Cannot run in swarm because privileged and capabilities not supported.

# TODO Get this to run under docker with net=host
# TODO Get this to run under podman with net=host
# TODO Get this to run as systemd service running with docker run or compose.
#      i.e. add 'systemctl start samba-dc-container.service' to /bootstrap/start
# TODO Get this to run as systemd service running with podman run.
# TODO Cleanup the environment vars/document the setup process.
# TODO Test bare metal (fedora/ubuntu/alpine).

DOMAIN="ad.clone1.com"
WORKGROUP="CLONE1"
MASTER_MACHINE="dc1"
SLAVE_MACHINE="dc2"
TIMEZONE="US/Central"
#USE_COMPOSE="true"
#DOCKER_MACHINE="docker-machine"

setup_samba() {

  echo "Setting up samba-dc vars on ssh host '$1' with internal IP '$2'."

  cat >samba-vars <<-__EOF__
	MASTER_IP="$MASTER_IP"
	HOST_IP="$2"
	DOMAIN="$DOMAIN"
	WORKGROUP="$WORKGROUP"
	TIMEZONE="$TIMEZONE"
	BACKEND="BIND9_DLZ"
	RUN_TESTS="true"
	__EOF__

  $DOCKER_MACHINE scp samba-vars $1:.
  $DOCKER_MACHINE scp docker-compose.yml $1:.
  $DOCKER_MACHINE ssh $1 "sudo mkdir -p /srv/samba-dc; sudo mv -f samba-vars /srv/samba-dc/; sudo chown root:root /srv/samba-dc/samba-vars"
  rm samba-vars
}

MASTER_IP=$($DOCKER_MACHINE ssh $MASTER_MACHINE "ip route get 8.8.8.8 | awk -F' src' 'NR==1{split(\$2,a,\" \"); print a[1]}'")
SLAVE_IP= $($DOCKER_MACHINE ssh $SLAVE_MACHINE  "ip route get 8.8.8.8 | awk -F' src' 'NR==1{split(\$2,a,\" \"); print a[1]}'")

setup_samba $MASTER_MACHINE $MASTER_IP
setup_samba $SLAVE_MACHINE  $SLAVE_IP

if [ -n "$USE_COMPOSE" ]; then
  echo "Adv19620d!" | docker login --username lochnerr --password-stdin
  #$DOCKER_MACHINE ssh $MASTER_MACHINE "sudo docker logout ; echo 'Alpha dog one Dee bang' | sudo docker login --username lochnerr --password-stdin ; sudo docker-compose up"
  $DOCKER_MACHINE ssh $MASTER_MACHINE "sudo docker-compose up"
  $DOCKER_MACHINE ssh $SLAVE_MACHINE  "sudo docker-compose up"
else
  $DOCKER_MACHINE ssh $MASTER_MACHINE "sudo docker run -d -m 512M --privileged --net=host --name samba-dc --rm -v /srv/samba-dc:/srv/samba-dc:rw lochnerr/samba-dc"
  $DOCKER_MACHINE ssh $SLAVE_MACHINE  "sudo docker run -d -m 512M --privileged --net=host --name samba-dc --rm -v /srv/samba-dc:/srv/samba-dc:rw lochnerr/samba-dc"
fi

echo "Done!"

