version: "3.2"

# Samba Active Directory Domain Controller automated test compose file.

# Note: This will not work in a docker swarm becuase swarm mode does not support the privileged option.

services:
  test-master:
    image: lochnerr/samba-dc:latest
    privileged: true
    command: /usr/local/bin/samba-start
    restart: "no"
    hostname: test-master.ad.example.com
    volumes:
      - dc1:/var/lib/samba

  test-slave:
    image: lochnerr/samba-dc:latest
    privileged: true
    command: /usr/local/bin/samba-start
    restart: "no"
    hostname: test-slave.ad.example.com
    volumes:
      - dc2:/var/lib/samba

  sut:
    image: lochnerr/samba-dc:latest
    command: /usr/local/bin/samba-tests-sut
    restart: "no"
    hostname: sut.ad.example.com
    volumes:
      - dc1:/var/lib/samba
      - dc2:/var/lib/slave
    depends_on:
      - test-master
      - test-slave

volumes:
  dc1:
  dc2:

