FROM ubuntu:18.04

LABEL MAINTAINER Richard Lochner, Clone Research Corp. <lochner@clone1.com> \
      org.label-schema.name = "samba-dc" \
      org.label-schema.description = "Samba Active Directory Domain Controller" \
      org.label-schema.vendor = "Clone Research Corp" \
      org.label-schema.usage = "https://github.com/lochnerr/samba-dc" \
      org.label-schema.url = "https://www.samba.org/" \
      org.label-schema.vcs-url = "https://github.com/lochnerr/samba-dc.git"


# Manditory packages:
# samba - the samba domain controller
# smbclient - smbclient (required for automated tests).
# krb5-config - required by samba.
# krb5-user - required by samba.
# attr TODO deleting???
# winbind - required by samba.
# libpam-winbind - required by samba.
# libnss-winbind - required by samba.
# libpam-krb5 - required by samba.
# bind9 - named (required to use the BIND9_DLZ backend)
# bind9utils - host (used in provisioning and automated tests)
# dnsutils - nsupdate (used in automated tests)
# iproute2 - ip (used in provisioning and automated tests)
# tdb-tools - tdbbackup (used to create backup of idmap)
# cifs-utils - mount.cifs (Required when provisioning a slave domain controller to access idmap backup on master)
# wget - wget (used to get current named.cache file from internet)
# net-tools - ifconfig, hostname (used in samba-set-vars)
# tzdata - time zones (allows setting time zone)
# Useful packages for debugging:
# iputils-ping - ping
# vim - vi
# inetutils-traceroute - traceroute
# nmap - nmap

RUN apt-get -y update \
 && DEBIAN_FRONTEND=noninteractive apt-get -y install \
        samba \
        smbclient \
        krb5-config \
        krb5-user \
        winbind \
        libpam-winbind \
        libnss-winbind \
        libpam-krb5 \
        bind9 \
        bind9utils \
        dnsutils \
        iproute2 \
        tdb-tools \
        cifs-utils \
        wget \
        net-tools \
        tzdata \
        iputils-ping \
        vim \
        inetutils-traceroute \
        nmap \
        systemd

# The persistent volume for samba and named.
VOLUME /srv/samba-dc

# Use systemd init to bring up services.
#CMD [ "/sbin/init" ]
CMD [ "/usr/local/bin/samba-start" ]

# Copy the script files and other artifacts.
COPY bin/. /usr/local/bin/

# Copy the systemd samba service.
COPY samba-ad-dc.service /usr/lib/systemd/system/

# Enable the systemd samba service.
##RUN systemctl enable samba-ad-dc.service

# Set systemd stop signal.
STOPSIGNAL SIGRTMIN+3

# Set the build labels.
# Do this last to allow build cacheing during development.
ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date = $BUILD_DATE \
      org.label-schema.vcs-ref = $VCS_REF

