version: "3.2"

# Samba Active Directory Domain Controller automated test compose file.

# When provisioning master domain controller, privileged is required.

services:
  test-master:
    image: lochnerr/samba-dc:latest
    privileged: true
    command: /usr/local/bin/samba-run
    restart: "no"
    hostname: test-master.ad.example.com
    volumes:
      - dc1:/var/lib/samba
    networks:
      - testnet

  test-slave:
    image: lochnerr/samba-dc:latest
    command: /usr/local/bin/samba-run
    restart: "no"
    hostname: test-slave.ad.example.com
    volumes:
      - dc2:/var/lib/samba
    networks:
      - testnet
    # Ensure that the master and slave get consistent IP's on restarts.
    depends_on:
      - test-master

  sut:
    image: lochnerr/samba-dc:latest
    command: /usr/local/bin/samba-tests-sut
    restart: "no"
    hostname: sut.ad.example.com
    volumes:
      - dc1:/var/lib/samba
      - dc2:/var/lib/slave
    networks:
      - testnet
    depends_on:
      - test-master
      - test-slave

volumes:
  dc1:
  dc2:

networks:
  testnet:

