ARG RELEASE
FROM systemd:fedora-$RELEASE

LABEL MAINTAINER Richard Lochner, Clone Research Corp. <lochner@clone1.com> \
      org.label-schema.name = "samba-dc" \
      org.label-schema.description = "Samba Active Directory Domain Controller" \
      org.label-schema.vendor = "Clone Research Corp" \
      org.label-schema.usage = "https://github.com/lochnerr/samba-dc" \
      org.label-schema.url = "https://www.samba.org/" \
      org.label-schema.vcs-url = "https://github.com/lochnerr/samba-dc.git"

# Manditory packages:
# samba-dc - the samba domain controller
# samba-client - required by samba.
# samba-winbind - required by samba.
# samba-dc-bind-dlz - required to use the BIND9_DLZ backend.
# krb5-workstation - required by samba.
# bind - named (required to use the BIND9_DLZ backend)
# bind-utils - host & nsupdate (used in provisioning and automated tests)
# iproute - ip (used in provisioning and automated tests)
# tdb-tools - tdbbackup (used to create backup of idmap)
# cifs-utils - mount.cifs (Required when provisioning a slave domain controller to access idmap backup on master)
# procps-ng - ps (Needed to determine if running under systemd, from systemd image)
# hostname - hostname (used in samba-set-vars)
# gawk - awk (previously included prior to fedora 42)
# socat - socat (used for system unit tests)
# systemd-container - systemd for containers (from systemd image).

# Useful packages for debugging:
# wget - wget (used to get current named.cache file from internet)
# iputils - ping
# net-tools - ifconfig
# findutils - find
# traceroute - traceroute
# nmap - nmap

RUN dnf -y install --nodocs \
        samba-dc \
        samba-client \
        samba-winbind \
        samba-dc-bind-dlz \
        krb5-workstation \
        bind \
        bind-utils \
        iproute \
        tdb-tools \
        cifs-utils \
        hostname \
        gawk \
        socat \
        wget \
        iputils \
        net-tools \
        findutils \
        traceroute \
        nmap \
        && \
    dnf -y clean all && \
    # Empty the yum cache.
    rm -rf /var/cache/dnf && \
    rm -rf /var/cache/yum && \
    true

# The persistent volume for samba and named.
VOLUME /var/lib/samba

# Use systemd init to bring up services.
CMD [ "/sbin/init" ]

# Copy the script files and other artifacts.
COPY bin/. /usr/local/bin/

# Copy the systemd samba service.
COPY samba-ad-dc.service /usr/lib/systemd/system/

# Do one-time samba configuration.
RUN . /usr/local/bin/samba-configure \
 && samba_configure container

# Set systemd stop signal.
STOPSIGNAL SIGRTMIN+3

# Set the build labels.
# Do this last to allow build cacheing during development.
ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date = $BUILD_DATE \
      org.label-schema.vcs-ref = $VCS_REF

