FROM alpine:3.16

LABEL MAINTAINER Richard Lochner, Clone Research Corp. <lochner@clone1.com> \
      org.label-schema.name = "samba-dc" \
      org.label-schema.description = "Samba Active Directory Domain Controller" \
      org.label-schema.vendor = "Clone Research Corp" \
      org.label-schema.usage = "https://github.com/lochnerr/samba-dc" \
      org.label-schema.url = "https://www.samba.org/" \
      org.label-schema.vcs-url = "https://github.com/lochnerr/samba-dc.git"

# Manditory packages:
# samba-dc - the samba domain controller
# py3-dnspython - needed by samba_upgradedns (as of alpine:3.10).
# krb5 - required by samba.
# bind - named (required to use the BIND9_DLZ backend)
# bind-tools - host (used in provisioning and automated tests)
# iproute2 - ip (used in provisioning and automated tests)
# tdb - tdbbackup (used to create backup of idmap)
# cifs-utils - mount.cifs (Required when provisioning a slave domain controller to access idmap backup on master)
# net-tools - ifconfig, hostname - hostname (used in samba-set-vars)
# tzdata - time zones (allows setting time zone)
# util-linux - mount (busybox mount does not return correct error codes needed in provisioning)
# bash - needed by start scripts.
# socat - socat (used for automated tests)
# openrc - openrc init system.

# Useful packages for debugging:
# nmap - nmap

RUN apk add --update  --no-cache \
        samba-dc \
        py3-dnspython \
        krb5 \
        bind \
        bind-tools \
        iproute2 \
        tdb \
        cifs-utils \
        net-tools \
        tzdata \
        util-linux \
        bash \
        socat \
        openrc \
        nmap 

# The persistent volume for samba and named.
VOLUME /var/lib/samba

# Use openrc init to bring up services.
CMD [ "/sbin/init" ]

# Enable OpenRC in Alpine.
RUN true \
    # Disable getty's
    && sed -i 's/^\(tty\d\:\:\)/#\1/g' /etc/inittab \
    && sed -i \
        # Change subsystem type to "docker"
        -e 's/#rc_sys=".*"/rc_sys="docker"/g' \
        # Allow all variables through
        -e 's/#rc_env_allow=".*"/rc_env_allow="\*"/g' \
        # Start crashed services
        -e 's/#rc_crashed_stop=.*/rc_crashed_stop=NO/g' \
        -e 's/#rc_crashed_start=.*/rc_crashed_start=YES/g' \
        # Define extra dependencies for services
        -e 's/#rc_provide=".*"/rc_provide="loopback net"/g' \
        /etc/rc.conf \
    # Remove unnecessary services
    && rm -f /etc/init.d/hwdrivers \
            /etc/init.d/hwclock \
            /etc/init.d/hwdrivers \
            /etc/init.d/modules \
            /etc/init.d/modules-load \
            /etc/init.d/modloop \
    # Can't do cgroups
    && sed -i 's/\tcgroup_add_service/\t#cgroup_add_service/g' /lib/rc/sh/openrc-run.sh \
    && sed -i 's/VSERVER/DOCKER/Ig' /lib/rc/sh/init.sh

# Copy the script files and other artifacts.
COPY bin/. /usr/local/bin/

# Copy the openrc samba service.
COPY samba-ad-dc /etc/init.d/
COPY alpine-syslog /etc/init.d/syslog

# Do one-time samba configuration.
RUN . /usr/local/bin/samba-configure \
 && samba_configure container

# Set systemd stop signal.
STOPSIGNAL TERM

# Set the build labels.
# Do this last to allow build cacheing during development.
ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date = $BUILD_DATE \
      org.label-schema.vcs-ref = $VCS_REF

