ARG DISTRO
ARG RELEASE
FROM systemd:$DISTRO-$RELEASE

LABEL MAINTAINER Richard Lochner, Clone Research Corp. <lochner@clone1.com> \
      org.label-schema.name = "samba-dc" \
      org.label-schema.description = "Samba Active Directory Domain Controller" \
      org.label-schema.vendor = "Clone Research Corp" \
      org.label-schema.usage = "https://github.com/lochnerr/samba-dc" \
      org.label-schema.url = "https://www.samba.org/" \
      org.label-schema.vcs-url = "https://github.com/lochnerr/samba-dc.git"

# Manditory packages:
# samba - the samba domain controller
# smbclient - smbclient (required for automated tests).
# winbind - required by samba.
# libpam-winbind - required by samba.
# libnss-winbind - required by samba.
# krb5-config - required by samba.
# krb5-user - required by samba.
# libpam-krb5 - required by samba.
# bind9 - named (required to use the BIND9_DLZ backend)
# bind9utils - host (used in provisioning and automated tests)
# dnsutils - nsupdate (used in automated tests)
# iproute2 - ip (used in provisioning and automated tests)
# tdb-tools - tdbbackup (used to create backup of idmap)
# socat - socat (used for automated tests)
# systemd-container - systemd for containers (from systemd image).

# Useful packages for debugging:
# wget - wget (used to get current named.cache file from internet)
# iputils-ping - ping
# net-tools - ifconfig, hostname (used in samba-set-vars)
# tzdata - time zones (allows setting time zone)
# vim - vi
# inetutils-traceroute - traceroute
# nmap - nmap

RUN apt-get -y update \
 && DEBIAN_FRONTEND=noninteractive apt-get -y install \
        samba \
        smbclient \
        winbind \
        libpam-winbind \
        libnss-winbind \
        krb5-config \
        krb5-user \
        libpam-krb5 \
        bind9 \
        bind9utils \
        dnsutils \
        iproute2 \
        tdb-tools \
        socat \
        wget \
        iputils-ping \
        net-tools \
        tzdata \
        vim \
        inetutils-traceroute \
        nmap

# The persistent volume for samba and named.
VOLUME /var/lib/samba

# Use systemd init to bring up services.
CMD [ "/lib/systemd/systemd" ]

# Copy the script files and other artifacts.
COPY bin/. /usr/local/bin/

# Do one-time samba configuration.
RUN \
  # Debian-like distros enable both samba and named on startup.
  # Rename their config files to prevent them from automatically running.
  # Container mounts can be used to enable them as needed.
  mv -f /etc/samba/smb.conf   /etc/samba/smb.conf.orig && \
  mv -f /etc/bind/named.conf  /etc/bind/named.conf.orig

# Set systemd stop signal.
STOPSIGNAL SIGRTMIN+3

# Set the build labels.
# Do this last to allow build cacheing during development.
ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date = $BUILD_DATE \
      org.label-schema.vcs-ref = $VCS_REF

