version: "2"

# Samba Active Directory Domain Controller automated test compose file.

# When provisioning a first (primary) domain controller, privileged is required.

services:

  primary:
    image: lochnerr/samba-dc:${DISTRO:-fedora}-${RELEASE:-latest}
    command: run-service samba-provision provision
    privileged: true
    restart: "no"
    hostname: primary.test.example.com
    volumes:
      test-samba:/sut
    environment:
      INIT: $INIT

  backup:
    image: lochnerr/samba-dc:${DISTRO:-fedora}-${RELEASE:-latest}
    command: run-service samba-provision join primary.test.example.com
    restart: "no"
    hostname: backup.test.example.com
    volumes:
      - test-samba:/sut
    environment:
      INIT: $INIT

  sut:
    build:
      dockerfile: Dockerfile-${DISTRO:-fedora}
      args:
        RELEASE: ${RELEASE:-latest}
    image: lochnerr/samba-dc:${DISTRO:-fedora}-${RELEASE:-latest}
    command: /usr/local/bin/samba-tests-sut
    restart: "no"
    hostname: sut.test.example.com
    volumes:
      - test-samba:/sut

volumes:
  test-samba:

