version: "3.2"

#sudo docker stack deploy -c docker-compose.test.yml samba-dc-testing

# sudo docker exec -ti stack_myservice.1.$(sudo docker service ps -f 'name=samba-dc-testing.1' stack_samba-dc-testing -q --no-trunc | head -n1) /bin/bash

services:
  dc1test:
    image: samba-dc:latest
    privileged: true
    #cap_add:
    #  - ALL
    command: /usr/local/bin/samba-start
    #command: /usr/local/bin/sleep-forever
    #command: /usr/bin/sh -c ". /usr/local/bin/samba-set-vars; set_samba_vars"
    restart: "no"
    #unsupported container_name: dc1
    #deploy:
    # One per node. Need to think about this.
    #  mode: global
    #  restart_policy:
    #    condition: on-failure
    #    delay: 30s
    #    max_attempts: 3
    #    window: 120s
    #unsupported network_mode: bridge
    hostname: dc1test.ad.example.com
    #environment:
    #  DOMAIN_ACTION: join
    #  INTERFACES: ${SAMBADC_INTERFACES:-lo eth0}
    #  REALM: ${SAMBA_REALM:-ad.example.com}
    #  TZ: ${TZ:-UTC}
    #  WORKGROUP: ${SAMBA_WORKGROUP:-WORKGROUP}
    volumes:
      - dc1:/srv/samba-dc
    #ports:
    #  - 1053:53
    #  - 1053:53/udp
    #  - 88:88
    #  - 88:88/udp
    #  - 135:135
    #  - 137-138:137-138/udp
    #  - 139:139
    #  - 389:389
    #  - 389:389/udp
    #  - 445:445
    #  - 464:464
    #  - 464:464/udp
    #  - 636:636
    #  - 3268-3269:3268-3269
    #  - 49152-49199
    #secrets:
    #  - samba-admin-password

  dc2test:
    image: samba-dc:latest
    # Provioning slave does not need privileged.
    #privileged: true
    #cap_add:
    #  - ALL
    command: /usr/local/bin/samba-start
    #command: /usr/local/bin/sleep-forever
    #command: /usr/bin/sh -c ". /usr/local/bin/samba-set-vars; set_samba_vars"
    restart: "no"
    #unsupported container_name: dc2
    #deploy:
    # One per node. Need to think about this.
    #  mode: global
    #  restart_policy:
    #    condition: on-failure
    #    delay: 30s
    #    max_attempts: 3
    #    window: 120s
    #unsupported network_mode: bridge
    hostname: dc2test.ad.example.com
    #environment:
    #  DOMAIN_ACTION: join
    #  INTERFACES: ${SAMBADC_INTERFACES:-lo eth0}
    #  REALM: ${SAMBA_REALM:-ad.example.com}
    #  TZ: ${TZ:-UTC}
    #  WORKGROUP: ${SAMBA_WORKGROUP:-WORKGROUP}
    volumes:
      - dc2:/srv/samba-dc
    #ports:
    #  - 1053:53
    #  - 1053:53/udp
    #  - 88:88
    #  - 88:88/udp
    #  - 135:135
    #  - 137-138:137-138/udp
    #  - 139:139
    #  - 389:389
    #  - 389:389/udp
    #  - 445:445
    #  - 464:464
    #  - 464:464/udp
    #  - 636:636
    #  - 3268-3269:3268-3269
    #  - 49152-49199
    #secrets:
    #  - samba-admin-password

  dc3test:
    image: samba-dc:latest
    command: /bin/sh -c ". /usr/local/bin/samba-set-vars; set_samba_vars; /usr/local/bin/sleep-forever"
    restart: "no"
    hostname: dc3test.ad.example.com

volumes:
  dc1:
  dc2:

#secrets:
#  samba-admin-password:
#    file: /var/adm/admin/secrets/samba-admin-password

