version: "2"

# Samba Active Directory Domain Controller automated test compose file.

# When provisioning master and slave domain controllers, privileged is required.
# On the slave it is needed to mount the master's sysvol.

services:

  test-master:
    image: lochnerr/samba-dc:latest
    privileged: true
    restart: "no"
    hostname: test-master.ad.example.com
    volumes:
      - test-master:/var/lib/samba

  test-slave:
    image: lochnerr/samba-dc:latest
    privileged: true
    restart: "no"
    hostname: test-slave.ad.example.com
    volumes:
      - test-slave:/var/lib/samba

  sut:
    image: lochnerr/samba-dc:latest
    command: /usr/local/bin/samba-tests-sut
    restart: "no"
    hostname: sut.ad.example.com
    volumes:
      - test-master:/var/lib/samba

volumes:
  test-master:
  test-slave:

